begin;

insert into updates (
  id, title, body, type, version, priority, published_at,
  summary, badge, cta_label, cta_href, details_href, image_url,
  is_active, is_sticky, audience, preview_payload, banner_payload
) values (
  'c058d069-ccb7-440a-ab2d-5210d0cd3559',
  'v2.04 Souqy Image Studio for Mobile / استوديو صور Souqy للموبايل',
  'Souqy can now generate image assets from the mobile app, support reference-image re-edits, select the best available image model, and return the generated asset directly to the user. أصبح بإمكان Souqy توليد الصور من تطبيق الموبايل، دعم إعادة تعديل الصور المرجعية، اختيار نموذج التوليد المناسب، وإرجاع الصورة للمستخدم مباشرة.',
  'feature',
  'v2.04',
  150,
  now(),
  'Generate and re-edit Souqy images from the iOS app. توليد وإعادة تعديل صور Souqy من تطبيق iOS.',
  'Souqy',
  'Open Souqy',
  '/account',
  '/account',
  '/changelog/v204-souqy-mobile-image.png',
  true,
  false,
  '{}'::jsonb,
  '{"kind":"souqy-mobile-image","route":"/account","image":"/changelog/v204-souqy-mobile-image.png","features":["mobile-generation","reference-editing","model-selection","generated-asset-return"],"languages":["en","ar"]}'::jsonb,
  '{}'::jsonb
) on conflict (id) do update
  set title = excluded.title,
      body = excluded.body,
      type = excluded.type,
      version = excluded.version,
      priority = excluded.priority,
      summary = excluded.summary,
      badge = excluded.badge,
      cta_label = excluded.cta_label,
      cta_href = excluded.cta_href,
      details_href = excluded.details_href,
      image_url = excluded.image_url,
      is_active = excluded.is_active,
      is_sticky = excluded.is_sticky,
      audience = excluded.audience,
      preview_payload = excluded.preview_payload,
      banner_payload = excluded.banner_payload,
      updated_at = now();

insert into updates (
  id, title, body, type, version, priority, published_at,
  summary, badge, cta_label, cta_href, details_href, image_url,
  is_active, is_sticky, audience, preview_payload, banner_payload
) values (
  '30003288-bfef-41e2-9619-7ecb4dacbdda',
  'v2.05 Smarter Souqy Chat and Storefront Generation / محادثة Souqy أذكى وتوليد أكثر استقرارا',
  'Souqy now auto-detects whether a request is advice or an actionable change, supports mobile chat, improves Arabic answers with Fanar, and adds repair logic for generated storefront builds. أصبح Souqy يكتشف تلقائيا هل الطلب استشارة أو تعديل قابل للتنفيذ، ويدعم محادثة الموبايل، ويحسن الردود العربية عبر Fanar، ويضيف إصلاحا تلقائيا عند فشل بناء المتجر.',
  'feature',
  'v2.05',
  149,
  now(),
  'Souqy chat now routes advice, actions, Arabic answers, and build repair more intelligently. أصبحت محادثة Souqy أذكى في الاستشارة والتعديل والردود العربية وإصلاح البناء.',
  'Souqy',
  'Open Souqy',
  '/account',
  '/account',
  '/changelog/v205-souqy-chat-generation.png',
  true,
  false,
  '{}'::jsonb,
  '{"kind":"souqy-chat-generation","route":"/account","image":"/changelog/v205-souqy-chat-generation.png","features":["auto-detect-mode","mobile-chat","fanar-arabic","build-repair"],"languages":["en","ar"]}'::jsonb,
  '{}'::jsonb
) on conflict (id) do update
  set title = excluded.title,
      body = excluded.body,
      type = excluded.type,
      version = excluded.version,
      priority = excluded.priority,
      summary = excluded.summary,
      badge = excluded.badge,
      cta_label = excluded.cta_label,
      cta_href = excluded.cta_href,
      details_href = excluded.details_href,
      image_url = excluded.image_url,
      is_active = excluded.is_active,
      is_sticky = excluded.is_sticky,
      audience = excluded.audience,
      preview_payload = excluded.preview_payload,
      banner_payload = excluded.banner_payload,
      updated_at = now();

insert into updates (
  id, title, body, type, version, priority, published_at,
  summary, badge, cta_label, cta_href, details_href, image_url,
  is_active, is_sticky, audience, preview_payload, banner_payload
) values (
  'c5fb2c1e-293e-4aa1-9980-b3e5c465062c',
  'v2.06 Arabic Dashboard Stability / استقرار لوحة التحكم العربية',
  'The Arabic dashboard translation layer now batches DOM updates so heavy pages like Products stay responsive after switching the platform to Arabic. تم تحسين طبقة ترجمة لوحة التحكم العربية حتى تعالج التغييرات على دفعات، فتظل الصفحات الثقيلة مثل المنتجات مستجيبة بعد تحويل المنصة للعربية.',
  'feature',
  'v2.06',
  148,
  now(),
  'Arabic Products now loads without the previous freeze. صفحة المنتجات العربية أصبحت تفتح بدون التعليق السابق.',
  'Arabic',
  'Open products',
  '/account/products',
  '/account/products',
  '/changelog/v206-arabic-dashboard-stability.png',
  true,
  false,
  '{}'::jsonb,
  '{"kind":"arabic-dashboard-stability","route":"/account/products","image":"/changelog/v206-arabic-dashboard-stability.png","features":["batched-translation","products-page","rtl-dashboard","responsiveness"],"languages":["en","ar"]}'::jsonb,
  '{}'::jsonb
) on conflict (id) do update
  set title = excluded.title,
      body = excluded.body,
      type = excluded.type,
      version = excluded.version,
      priority = excluded.priority,
      summary = excluded.summary,
      badge = excluded.badge,
      cta_label = excluded.cta_label,
      cta_href = excluded.cta_href,
      details_href = excluded.details_href,
      image_url = excluded.image_url,
      is_active = excluded.is_active,
      is_sticky = excluded.is_sticky,
      audience = excluded.audience,
      preview_payload = excluded.preview_payload,
      banner_payload = excluded.banner_payload,
      updated_at = now();

insert into updates (
  id, title, body, type, version, priority, published_at,
  summary, badge, cta_label, cta_href, details_href, image_url,
  is_active, is_sticky, audience, preview_payload, banner_payload
) values (
  'f4d7b370-437d-4979-ad74-4733d5ebffa7',
  'v2.07 Email and WhatsApp Reliability / موثوقية الإيميل وواتساب',
  'Order emails, mobile alerts, and WhatsApp notifications are now awaited inside checkout flows, include SkipCash and SADAD orders, force the WhatsApp channel for phone templates, and log clear failure or skipped-send reasons. أصبحت إيميلات الطلبات، تنبيهات الموبايل، ورسائل واتساب تنتظر التنفيذ داخل عملية الطلب، وتشمل طلبات SkipCash وSADAD، وتستخدم قناة WhatsApp صراحة، مع تسجيل واضح لأسباب الفشل أو التخطي.',
  'feature',
  'v2.07',
  147,
  now(),
  'Checkout notifications now run more reliably and expose clear provider reasons. إشعارات الطلبات أصبحت أكثر موثوقية وتعرض أسباب المزود بوضوح.',
  'Notify',
  'View orders',
  '/account/orders',
  '/account/orders',
  '/changelog/v207-email-whatsapp-reliability.png',
  true,
  false,
  '{}'::jsonb,
  '{"kind":"email-whatsapp-reliability","route":"/account/orders","image":"/changelog/v207-email-whatsapp-reliability.png","features":["awaited-email","awaited-whatsapp","skipcash-sadad","failure-reasons"],"languages":["en","ar"]}'::jsonb,
  '{}'::jsonb
) on conflict (id) do update
  set title = excluded.title,
      body = excluded.body,
      type = excluded.type,
      version = excluded.version,
      priority = excluded.priority,
      summary = excluded.summary,
      badge = excluded.badge,
      cta_label = excluded.cta_label,
      cta_href = excluded.cta_href,
      details_href = excluded.details_href,
      image_url = excluded.image_url,
      is_active = excluded.is_active,
      is_sticky = excluded.is_sticky,
      audience = excluded.audience,
      preview_payload = excluded.preview_payload,
      banner_payload = excluded.banner_payload,
      updated_at = now();

insert into updates (
  id, title, body, type, version, priority, published_at,
  summary, badge, cta_label, cta_href, details_href, image_url,
  is_active, is_sticky, audience, preview_payload, banner_payload
) values (
  '1e912c65-50e6-4f2d-8b27-682799db10a9',
  'v2.08 Mobile Checkout and Payment Setup / إعدادات الدفع في الموبايل',
  'Mobile checkout settings now support SADAD credential verification, encrypted storage, better payment-method updates, and clearer audit history for online payment changes. إعدادات الدفع في تطبيق الموبايل أصبحت تدعم التحقق من بيانات SADAD، تخزينها بشكل مشفر، تحديث طرق الدفع بشكل أوضح، وتسجيل التغييرات في سجل التدقيق.',
  'feature',
  'v2.08',
  146,
  now(),
  'Set up SADAD from mobile checkout with verification and encrypted storage. يمكن إعداد SADAD من تطبيق الموبايل مع التحقق والتخزين المشفر.',
  'Payments',
  'Open checkout',
  '/account/settings/checkout',
  '/account/settings/checkout',
  '/changelog/v208-mobile-payments.png',
  true,
  false,
  '{}'::jsonb,
  '{"kind":"mobile-payments","route":"/account/settings/checkout","image":"/changelog/v208-mobile-payments.png","features":["sadad-verification","encrypted-credentials","mobile-checkout","payment-audit"],"languages":["en","ar"]}'::jsonb,
  '{}'::jsonb
) on conflict (id) do update
  set title = excluded.title,
      body = excluded.body,
      type = excluded.type,
      version = excluded.version,
      priority = excluded.priority,
      summary = excluded.summary,
      badge = excluded.badge,
      cta_label = excluded.cta_label,
      cta_href = excluded.cta_href,
      details_href = excluded.details_href,
      image_url = excluded.image_url,
      is_active = excluded.is_active,
      is_sticky = excluded.is_sticky,
      audience = excluded.audience,
      preview_payload = excluded.preview_payload,
      banner_payload = excluded.banner_payload,
      updated_at = now();

insert into updates (
  id, title, body, type, version, priority, published_at,
  summary, badge, cta_label, cta_href, details_href, image_url,
  is_active, is_sticky, audience, preview_payload, banner_payload
) values (
  '4c522675-d5b2-4eb2-a8d2-62130bbe2d29',
  'v2.09 Builder, Components, and Platform Updates / تحديثات المحرر والمكونات والمنصة',
  'Souqna now includes a component library showcase, new demo assets, safer storefront rendering, improved sidebar and topbar UI, Fanar and Cranl runtime support, and updated documentation. تمت إضافة معرض لمكونات المحرر، أصول تجريبية جديدة، عرض أكثر أمانا للمتاجر، تحسينات للواجهة الجانبية والعلوية، دعم Fanar وCranl، وتحديثات للوثائق.',
  'feature',
  'v2.09',
  145,
  now(),
  'Builder components, runtime support, UI polish, and docs are improved together. تم تحسين مكونات المحرر ودعم التشغيل والواجهة والوثائق معا.',
  'Builder',
  'Open builder',
  '/account/builder',
  '/account/builder',
  '/changelog/v209-builder-platform.png',
  true,
  false,
  '{}'::jsonb,
  '{"kind":"builder-platform","route":"/account/builder","image":"/changelog/v209-builder-platform.png","features":["component-library","demo-assets","safe-rendering","fanar-cranl","ui-polish"],"languages":["en","ar"]}'::jsonb,
  '{}'::jsonb
) on conflict (id) do update
  set title = excluded.title,
      body = excluded.body,
      type = excluded.type,
      version = excluded.version,
      priority = excluded.priority,
      summary = excluded.summary,
      badge = excluded.badge,
      cta_label = excluded.cta_label,
      cta_href = excluded.cta_href,
      details_href = excluded.details_href,
      image_url = excluded.image_url,
      is_active = excluded.is_active,
      is_sticky = excluded.is_sticky,
      audience = excluded.audience,
      preview_payload = excluded.preview_payload,
      banner_payload = excluded.banner_payload,
      updated_at = now();

commit;
