import type { StudioTab } from './types';

export type StudioCopy = ReturnType<typeof studioCopy>;

export function studioCopy(isRtl: boolean) {
  return isRtl
    ? {
        assistantName: 'Souqy AI',
        assetsCount: 'أصول',
        attach: 'إرفاق ملف',
        attachedReference: 'صورة مرفقة',
        attachedReferences: 'الصور المرفقة',
        bleed: 'هوامش طباعة',
        catalog: 'منتجات الكتالوج',
        chatCommandTitle: 'اسأل سوقي',
        chatEmptyResult: 'أنهى المساعد الذكي دون إجابة واضحة.',
        chatFailed: 'تعذر على المساعد الذكي إكمال الطلب.',
        chatPlaceholder: 'اسأل سوقي عن أفكار الحملات أو البرومبتات أو نصائح المتجر...',
        chatReady: 'وصل رد سوقي.',
        chatStarters: [
          'خطط حملة رمضان لقائمة منتجاتي',
          'اكتب وصفا جذابا لأفضل منتج عندي',
          'اقترح أفكار بوستات انستغرام لهذا الأسبوع',
          'كيف أحسن صفحة متجري لزيادة المبيعات؟',
        ],
        chatStartersTitle: 'جرب تسأل سوقي',
        chatStopped: 'أوقفت الرد.',
        stop: 'إيقاف',
        chatSystemPrompt:
          'You are Souqy Studio, a practical AI assistant for storefront owners creating ads, posters, product visuals, and launch campaigns. Keep answers concise, specific, and ready to use.',
        chatThinking: 'سوقي يفكر...',
        chatTimedOut: 'المساعد الذكي ما زال يعمل. حاول التحقق بعد قليل.',
        clearerChatPrompt: 'اكتب سؤالا لسوقي أولا.',
        clearerPrompt: 'اكتب وصفا أوضح للتصميم.',
        clearerWebPrompt: 'صف تغيير الموقع بمزيد من التفصيل.',
        commandTitle: 'أنشئ تصميما',
        contextClose: 'إغلاق لوحة السياق',
        contextOpen: 'فتح لوحة السياق',
        contextTitle: 'لوحة السياق',
        conversation: 'محادثة سوقي',
        creating: 'سوقي يصمم الأصل...',
        creativity: 'قوة الإبداع',
        download: 'تحميل',
        editCommandTitle: 'عدّل صورة',
        editNeedsReference: 'اختر أو ارفع صورة قبل التعديل.',
        editPromptPlaceholder: 'صف التعديلات التي تريدها من سوقي...',
        editPromptSeed: 'حوّل هذا التصميم إلى إعلان متجر فاخر مع الحفاظ على التصميم الأصلي.',
        editReady: 'جاهز لتعديل هذا الأصل.',
        editReferenceFailed: 'تعذر تجهيز هذا الأصل للتعديل.',
        editSelectBody: 'ارفع صورة مرجعية أو اختر أصلا حديثا من السجل.',
        editSelectTitle: 'اختر أصلا للتعديل',
        editThis: 'تعديل',
        eyebrow: 'استوديو سوقي',
        generateShort: 'إنشاء',
        heroBody: 'اكتب طلبك بالأسفل لبدء الإنشاء',
        heroTitle: 'جاهز للإنشاء',
        high: 'عالية',
        instructions: 'تعليمات الهوية',
        instructionsPlaceholder: 'فاخر، هادئ، مناسب للعربية، إضاءة دافئة...',
        libraryError: 'تعذر تحميل مكتبة سوقي.',
        libraryReady: 'تم تحديث السجل.',
        live: 'حي',
        loadingHistory: 'نحمّل الأصول المحفوظة...',
        loadingProjects: 'نحمّل المشاريع...',
        model: 'النموذج',
        modeHints: {
          projects: 'إدارة جلسات العمل',
          create: 'توليد أصول جديدة',
          edit: 'تعديل بصورة مرجعية',
          chat: 'أفكار ونصائح',
          web: 'إعادة تصميم المتجر',
          history: 'كل المخرجات المحفوظة',
        } satisfies Record<StudioTab, string>,
        modeLabels: {
          projects: 'المشاريع',
          create: 'إنشاء',
          edit: 'تعديل',
          chat: 'محادثة',
          web: 'الويب',
          history: 'السجل',
        } satisfies Record<StudioTab, string>,
        newProject: 'جديد',
        noAssets: 'ستظهر أعمالك الأخيرة هنا.',
        noProducts: 'لا توجد منتجات مرتبطة بعد.',
        noProjects: 'لا توجد مشاريع بعد.',
        noSelection: 'اختر أصلا من اللوحة.',
        noStorefront: 'بدون متجر محدد',
        openImage: 'فتح الصورة',
        openStorefront: 'فتح',
        preparing: 'نجهز مكتبة الأصول...',
        preparingEdit: 'نجهز هذا الأصل للتعديل...',
        print: 'للطباعة',
        projectNamePlaceholder: 'اسم المشروع',
        projectNameRequired: 'أدخل اسم المشروع أولا.',
        projectOpened: 'تم فتح المشروع.',
        projectStarted: 'تم بدء المشروع.',
        projectsError: 'تعذر تحميل مشاريع سوقي.',
        projectsReady: 'تم تحديث المشاريع.',
        promptPlaceholder: 'اكتب ما تريد من سوقي أن يصممه لهذا البراند...',
        quality: 'الدقة',
        quickPromptsLabel: 'أوامر سريعة',
        referenceModelUnsupported: 'هذا النموذج لا يدعم تعديل الصور المرجعية في هذا المسار.',
        refresh: 'تحديث',
        removeReference: 'إزالة المرجع',
        resultReady: 'أصبح التصميم جاهزا.',
        selected: 'الأصل المحدد',
        send: 'إرسال',
        sessionLabel: 'الجلسة',
        settings: 'الإعدادات',
        size: 'المقاس',
        standard: 'قياسية',
        statusIdle: 'جاهز لاستقبال الأمر التالي.',
        statusLabel: 'الحالة',
        storefront: 'المتجر',
        studioCommand: 'أمر الاستوديو',
        template: 'النوع',
        webBody: 'عاين المتجر المحدد داخل إطار متصفح حي.',
        webCommandTitle: 'صمّم هذا الموقع',
        webDesign: 'تصميم الموقع',
        webDesignFailed: 'تعذر إعادة تصميم الموقع. حاول مجددا.',
        webDesigning: 'سوقي يصمم واجهة المتجر...',
        webDesignReady: 'تمت إعادة تصميم الموقع وتحديث المعاينة.',
        webPromptHint: 'اطلب تغييرات في التخطيط أو الألوان أو الأقسام أو النصوص أو عرض المنتجات.',
        webPromptPlaceholder: 'اكتب لسوقي كيف يعيد تصميم هذا المتجر...',
        workspace: 'مساحة العمل',
        you: 'أنت',
      }
    : {
        assistantName: 'Souqy AI',
        assetsCount: 'assets',
        attach: 'Attach file',
        attachedReference: 'Attached image',
        attachedReferences: 'Attached images',
        bleed: 'Print bleed',
        catalog: 'Catalog products',
        chatCommandTitle: 'Ask Souqy',
        chatEmptyResult: 'The AI assistant finished without a readable answer.',
        chatFailed: 'The AI assistant failed.',
        chatPlaceholder: 'Ask Souqy for campaign ideas, prompts, or storefront advice...',
        chatReady: 'AI replied.',
        chatStarters: [
          'Plan a Ramadan campaign for my product lineup',
          'Write a compelling description for my best seller',
          'Suggest Instagram post ideas for this week',
          'How do I improve my storefront to sell more?',
        ],
        chatStartersTitle: 'Try asking Souqy',
        chatStopped: 'Stopped the response.',
        stop: 'Stop',
        chatSystemPrompt:
          'You are Souqy Studio, a practical AI assistant for storefront owners creating ads, posters, product visuals, and launch campaigns. Keep answers concise, specific, and ready to use.',
        chatThinking: 'Souqy is thinking...',
        chatTimedOut: 'The AI assistant is still working. Try checking again in a moment.',
        clearerChatPrompt: 'Ask Souqy something first.',
        clearerPrompt: 'Write a clearer design prompt first.',
        clearerWebPrompt: 'Describe the website change in a little more detail.',
        commandTitle: 'Create an asset',
        contextClose: 'Close context panel',
        contextOpen: 'Open context panel',
        contextTitle: 'Context panel',
        conversation: 'Souqy conversation',
        creating: 'Souqy is creating the asset...',
        creativity: 'Creative strength',
        download: 'Download',
        editCommandTitle: 'Edit an image',
        editNeedsReference: 'Choose or upload an image before editing.',
        editPromptPlaceholder: 'Describe the changes you want Souqy to make...',
        editPromptSeed:
          'Polish this into a premium storefront ad while preserving the original design.',
        editReady: 'Ready to edit this asset.',
        editReferenceFailed: 'Could not prepare this asset for editing.',
        editSelectBody: 'Upload a reference or choose a recent asset from History.',
        editSelectTitle: 'Choose an asset to edit',
        editThis: 'Edit',
        eyebrow: 'Souqy Studio',
        generateShort: 'Generate',
        heroBody: 'Enter a prompt below to start generating',
        heroTitle: 'Ready to Create',
        high: 'High',
        instructions: 'Brand instructions',
        instructionsPlaceholder: 'Premium, quiet, Arabic-friendly, warm keylight...',
        libraryError: 'Could not load Souqy library.',
        libraryReady: 'History refreshed.',
        live: 'Live',
        loadingHistory: 'Loading saved assets...',
        loadingProjects: 'Loading projects...',
        model: 'Model',
        modeHints: {
          projects: 'Manage work sessions',
          create: 'Generate new assets',
          edit: 'Edit with a reference',
          chat: 'Ideas and guidance',
          web: 'Redesign the storefront',
          history: 'Every saved output',
        } satisfies Record<StudioTab, string>,
        modeLabels: {
          projects: 'Projects',
          create: 'Create',
          edit: 'Edit',
          chat: 'Chat',
          web: 'Web',
          history: 'History',
        } satisfies Record<StudioTab, string>,
        newProject: 'New',
        noAssets: 'Recent work will appear here.',
        noProducts: 'No catalog products connected yet.',
        noProjects: 'No projects yet.',
        noSelection: 'Select an output from the canvas.',
        noStorefront: 'No storefront selected',
        openImage: 'Open image',
        openStorefront: 'Open',
        preparing: 'Preparing the asset library...',
        preparingEdit: 'Preparing this asset for editing...',
        print: 'Print',
        projectNamePlaceholder: 'Project name',
        projectNameRequired: 'Enter a project name first.',
        projectOpened: 'Project opened.',
        projectStarted: 'Project started.',
        projectsError: 'Could not load Souqy projects.',
        projectsReady: 'Projects refreshed.',
        promptPlaceholder: 'Enter a prompt below to start generating',
        quality: 'Quality',
        quickPromptsLabel: 'Quick commands',
        referenceModelUnsupported:
          'This model does not support reference-image edits in this surface.',
        refresh: 'Refresh',
        removeReference: 'Remove reference',
        resultReady: 'Your asset is ready.',
        selected: 'Selected asset',
        send: 'Send',
        sessionLabel: 'Session',
        settings: 'Settings',
        size: 'Format',
        standard: 'Standard',
        statusIdle: 'Ready for the next command.',
        statusLabel: 'Status',
        storefront: 'Storefront',
        studioCommand: 'Studio Command',
        template: 'Type',
        webBody: 'Preview the selected storefront in a live browser frame.',
        webCommandTitle: 'Design this website',
        webDesign: 'Design website',
        webDesignFailed: 'Could not redesign the website. Try again.',
        webDesigning: 'Souqy is designing the storefront...',
        webDesignReady: 'Website redesigned. Preview refreshed.',
        webPromptHint: 'Ask for layout, colors, sections, copy, or product presentation changes.',
        webPromptPlaceholder: 'Tell Souqy how to redesign this storefront...',
        workspace: 'Workspace',
        you: 'You',
      };
}
