/**
 * English copy. Mirrored exactly in copy.ar.ts. Update both together.
 *
 * Brand framing rules:
 *  - "A bilingual commerce workspace designed in Doha for Gulf storefronts."
 *  - Product-led SaaS, not an agency or home-business niche.
 *  - No fabricated stats, headcounts, client names, or scarcity.
 */
export const copyEn = {
  meta: {
    framing: 'BUILT IN QATAR FOR THE GULF',
    framingFull: 'BILINGUAL COMMERCE WORKSPACE · DESIGNED IN DOHA',
    established: 'BUILT IN QATAR — 2026',
    vision: 'Built for Gulf commerce',
    visionShort: 'Gulf-first commerce workspace',
    siteName: 'Souqna',
    titleSuffix: 'Souqna — bilingual commerce workspace for Gulf storefronts',
    description:
      'Souqna helps founders launch and operate bilingual Gulf storefronts with the builder, catalogue, orders, payments, apps, and growth work in one place.',
  },

  nav: {
    work: 'AI',
    process: 'Builder',
    operations: 'Operations',
    discover: 'Apps',
    atelier: 'Souqy',
    pricing: 'Pricing',
    journal: 'Journal',
    contact: 'Start',
    cta: 'Generate store',
    skipToContent: 'Skip to content',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },

  hero: {
    eyebrow: 'the premise',
    line1: 'From an idea',
    line2a: 'to a',
    line2b: 'real',
    line2c: 'business.',
    arabicEcho: '',
    body: 'A bilingual commerce workspace designed in Doha. Launch a storefront, manage the catalogue, and keep daily store work in one calm product surface.',
    primaryCta: 'Begin a project',
    secondaryCta: 'or — see how it goes ↓',
    flowSteps: ['Begin', 'Build', 'Tune', 'Publish'],
    flowAriaLabel: 'How it goes — four steps from idea to live storefront.',
  },

  homeSaas: {
    hero: {
      eyebrow: 'Bilingual commerce workspace · designed in Doha',
      title: 'Launch and run the storefront from one place.',
      body: 'Shape a bilingual storefront, catalogue, order flow, and operating dashboard without separating the launch from the work that follows.',
      promptLabel: 'Describe the store you want to launch',
      promptPlaceholder: 'Describe your brand, products, and market',
      promptExample:
        'Create a bilingual skincare store for the GCC with premium bundles and WhatsApp checkout.',
      generateCta: 'Start your build',
      primaryCta: 'Start building',
      secondaryCta: 'View dashboard',
      previewStatus: 'live generation',
      aiPanelTitle: 'AI build plan',
      brandPanelTitle: 'Brand system',
      brandSample: 'Noura Skin · نورا سكن',
      storefrontUrl: 'noura.souqna.qa',
      bilingual: 'Arabic + English',
      liveLabel: 'generated storefront',
      storefrontTitle: 'A premium skincare storefront for the Gulf.',
      products: ['Glow serum', 'Travel kit'],
      progress: ['Brand direction', 'Storefront layout', 'Products and SEO', 'Ready to publish'],
      chips: ['Arabic + English parity', 'GCC payments', 'AI brand assets', 'Commerce ops'],
      metrics: [
        { label: 'SEO score', value: '94' },
        { label: 'Orders', value: '128' },
        { label: 'Assets', value: '36' },
      ],
    },
    ai: {
      eyebrow: 'AI generation',
      title: 'From prompt to complete commerce system.',
      body: 'Souqna generates the surfaces a modern store needs: identity, storefront, banners, product copy, and growth recommendations.',
      cards: [
        {
          icon: 'logo',
          title: 'Logo generation',
          body: 'Create directionally strong marks and lockups for bilingual brands.',
          status: 'brand',
          progress: '86%',
        },
        {
          icon: 'storefront',
          title: 'Storefront generation',
          body: 'Generate responsive sections, product grids, content, and launch-ready pages.',
          status: 'build',
          progress: '92%',
        },
        {
          icon: 'banner',
          title: 'Marketing assets',
          body: 'Produce campaign banners, launch visuals, and reusable brand graphics.',
          status: 'assets',
          progress: '78%',
        },
        {
          icon: 'copy',
          title: 'Product descriptions',
          body: 'Write Arabic and English product content with SEO structure built in.',
          status: 'copy',
          progress: '88%',
        },
        {
          icon: 'recommendations',
          title: 'AI recommendations',
          body: 'Get pricing, merchandising, and conversion suggestions from your store data.',
          status: 'growth',
          progress: '74%',
        },
      ],
      beforeLabel: 'before',
      beforeBody: 'A blank template, disconnected product data, and manual translation work.',
      afterLabel: 'after',
      afterTitle: 'Generated brand system',
      afterBody:
        'A live store direction with bilingual copy, visual assets, and commerce-ready sections.',
      hoverCopy: 'Generate {0} and launch {1} without switching tools.',
      hoverTargets: ['brand assets', 'storefronts'],
    },
    builder: {
      eyebrow: 'website builder',
      title: 'A visual builder designed for bilingual commerce.',
      body: 'Edit the generated storefront with responsive panels, templates, drag-and-drop sections, and Arabic-English content parity.',
      rails: { blocks: 'blocks', settings: 'settings' },
      blocks: ['Hero', 'Products', 'Bundles', 'Reviews', 'WhatsApp CTA', 'Policies'],
      settings: ['Theme', 'Layout', 'Arabic copy', 'SEO', 'Checkout', 'Domain'],
      canvasLabel: 'builder canvas',
      deviceLabel: 'responsive',
      previewEyebrow: 'campaign page',
      previewTitle: 'Launch a store that feels ready on day one.',
      breakpoints: ['Mobile', 'Tablet', 'Desktop'],
      features: [
        {
          icon: 'editor',
          title: 'Drag-and-drop editing',
          body: 'Move sections, tune layouts, and refine generated pages without code.',
        },
        {
          icon: 'responsive',
          title: 'Responsive editing',
          body: 'Preview and adjust product pages across mobile, tablet, and desktop.',
        },
        {
          icon: 'templates',
          title: 'Modern templates',
          body: 'Start from SaaS-grade commerce layouts instead of decorative themes.',
        },
        {
          icon: 'bilingual',
          title: 'Bilingual parity',
          body: 'Arabic and English stay first-class across copy, layout, and storefront chrome.',
        },
      ],
    },
    operations: {
      eyebrow: 'commerce operations',
      title: 'Run the store, not just the website.',
      body: 'Products, orders, customers, discounts, analytics, and domains live in one operating layer built for Gulf ecommerce teams.',
      dashboardTitle: 'Revenue and growth dashboard',
      metrics: [
        { label: 'Revenue', value: 'QR 42.8k', delta: '+18% this month' },
        { label: 'Conversion', value: '4.8%', delta: '+0.9 pts' },
        { label: 'Repeat buyers', value: '31%', delta: '+7% cohort' },
      ],
      features: [
        {
          icon: 'products',
          title: 'Products and inventory',
          body: 'Manage catalogues, bundles, imports, visuals, and bilingual product data.',
        },
        {
          icon: 'orders',
          title: 'Orders and customers',
          body: 'Track orders, customer records, discounts, and support moments together.',
        },
        {
          icon: 'analytics',
          title: 'Analytics and growth',
          body: 'See performance, channels, and recommendations without leaving the dashboard.',
        },
        {
          icon: 'domains',
          title: 'Domains and infrastructure',
          body: 'Publish to Souqna subdomains or custom domains with regional readiness.',
        },
      ],
    },
    souqy: {
      eyebrow: 'Souqy AI',
      title: 'Your AI commerce operator.',
      body: 'Souqy works across SEO, descriptions, bulk edits, analytics, storefront revisions, and growth recommendations.',
      operatorLabel: 'operator mode',
      panelTitle: 'Souqy assistant',
      messages: [
        'I found 18 products missing Arabic SEO descriptions.',
        'Generate improved descriptions and apply to the summer collection.',
        'Done. I also recommend moving bundles above single products on mobile.',
      ],
      actions: [
        {
          icon: 'seo',
          title: 'SEO optimizer',
          body: 'Rewrite titles, descriptions, and metadata for bilingual search intent.',
        },
        {
          icon: 'copy',
          title: 'Product copy generator',
          body: 'Create consistent product descriptions, specs, and selling points.',
        },
        {
          icon: 'bulk',
          title: 'Bulk editor',
          body: 'Update catalogues, collections, and storefront sections in one action.',
        },
        {
          icon: 'insights',
          title: 'Analytics assistant',
          body: 'Translate store data into clear next steps for conversion and growth.',
        },
        {
          icon: 'revisions',
          title: 'AI revisions',
          body: 'Ask for a more premium hero, better product order, or stronger campaign page.',
        },
        {
          icon: 'growth',
          title: 'Growth advisor',
          body: 'Plan campaigns, offers, and customer moments for Gulf audiences.',
        },
      ],
    },
    integrations: {
      eyebrow: 'apps and integrations',
      title: 'Connect the tools Gulf teams already use.',
      body: 'Souqna’s app layer brings marketing, messaging, payments, and automation into the commerce operating system.',
      apps: [
        { name: 'Meta', body: 'Campaign pixels, catalogues, and paid acquisition signals.' },
        { name: 'Instagram', body: 'Social selling surfaces for product discovery and launches.' },
        { name: 'WhatsApp', body: 'Customer conversations and checkout-ready messaging paths.' },
        { name: 'SkipCash', body: 'Regional payment readiness for Gulf storefronts.' },
        { name: 'Klaviyo', body: 'Lifecycle messaging, segmentation, and growth automations.' },
        { name: 'Mailchimp', body: 'Email campaigns and marketing lists for early teams.' },
      ],
    },
    finalCta: {
      eyebrow: 'ready to launch',
      title: 'Generate the next Gulf ecommerce brand.',
      body: 'Start with a prompt. Leave with a bilingual storefront, AI brand system, and operating dashboard built to scale.',
      primaryCta: 'Start your build',
      secondaryCta: 'Open dashboard',
    },
  },

  marquee: {
    items: ['Strategy', 'Prototype', 'Build', 'Launch', 'Accompany'],
  },

  pillars: {
    eyebrow: 'the pillars',
    title:
      'Four pillars. {italic}One vision.{/italic} A console for the businesses Qatar is becoming.',
    titleItalic: 'One vision.',
    aside: 'with Qatar Vision 2030',
    asideLabel: 'aligned',
    items: {
      human: {
        roman: 'I',
        name: 'Human development',
        body: 'AI tooling that extends the capability of Gulf commerce teams — never replaces their judgment.',
        note: 'Bilingual agents · assistive interfaces · training',
      },
      social: {
        roman: 'II',
        name: 'Social development',
        body: 'Services that honour family, privacy and the Arabic language at their core — not as a translation layer.',
        note: 'Arabic-first products · cultural nuance · trust',
      },
      economic: {
        roman: 'III',
        name: 'Economic development',
        body: 'Diversifying beyond hydrocarbons through knowledge-economy businesses that can compete on quality, globally.',
        note: 'New SMEs · productivity · export-ready',
      },
      environmental: {
        roman: 'IV',
        name: 'Environmental development',
        body: 'Efficient operations by default — AI that cuts waste from logistics, energy and supply chains before anything else.',
        note: 'Optimisation · conservation · stewardship',
      },
    },
  },

  process: {
    eyebrow: 'how it goes',
    title:
      'Four quiet steps. From an idea to a {italic}live storefront{/italic} — and an atelier that stays on the line afterwards.',
    titleItalic: 'live storefront',
    phases: {
      begin: {
        roman: 'I',
        name: 'Begin',
        time: '~ 2 min',
        caption: 'souqna.qa/begin',
        body: 'Pick a name and an address. We claim the slug as you type, suggest a template, and pull together your first storefront in the time it takes to brew tea.',
      },
      build: {
        roman: 'II',
        name: 'Build',
        time: '~ 10 min',
        caption: 'dashboard · builder',
        body: 'Drag blocks onto the canvas — hero, products, contact, hours. Edit copy in either language. The inspector tunes every detail without ever opening code.',
      },
      tune: {
        roman: 'III',
        name: 'Tune',
        time: '~ 10 min',
        caption: 'dashboard · theme + products',
        body: 'A palette, a typeface pairing, your catalogue. Add products from a CSV or one by one. Quiet defaults you can override, but rarely need to.',
      },
      publish: {
        roman: 'IV',
        name: 'Publish',
        time: 'instant',
        caption: 'slug.souqna.qa · live',
        body: 'One press. Your storefront is live at slug.souqna.qa — bilingual, mobile-ready, payment-ready. The atelier stays on the line for everything that comes next.',
      },
    },
  },

  atelier: {
    eyebrow: 'the atelier',
    title:
      'Not a template site. Not an agency. A product platform {italic}built in Qatar for the Gulf{/italic}.',
    titleItalic: 'built in Qatar for the Gulf',
    sub: 'A modern operating layer for Gulf ecommerce teams that want AI-native speed without losing control.',
    values: [
      'We write our own code, copy, and contracts. No outsourced layers between you and the people who build.',
      'We bill in Qatari Riyal and answer in your dialect — no exceptions.',
      'We stay on the line for as long as the business runs. Partnership, not just handover.',
    ],
  },

  principles: {
    eyebrow: 'principles',
    items: [
      { title: 'Arabic first, not as a footnote.', note: 'Every surface, every flow.' },
      { title: 'Owned by the founder, tuned by us.', note: 'No vendor lock-in.' },
      { title: 'Continuous support, not a hand-off.', note: 'For as long as the business runs.' },
      {
        title: 'Aligned with Qatar National Vision 2030.',
        note: 'Human · social · economic · environmental.',
      },
    ],
  },

  journal: {
    eyebrow: 'journal',
    title: 'Field notes from the {italic}atelier{/italic}.',
    titleItalic: 'atelier',
    indexLink: 'All entries',
    empty: {
      title: 'The atelier is still writing.',
      body: 'The first dispatches will appear here in the spring. Until then, the work speaks.',
    },
    readSuffix: 'min',
  },

  pricing: {
    eyebrow: 'pricing',
    title: 'Plans for storefronts that need room to operate.',
    titleItalic: 'AI-powered commerce.',
    sub: 'Start with a generated storefront, then scale into AI operations, apps, and team workflows as your business grows.',
    currency: 'QR',
    perMonth: '/ month',
    featuredLabel: 'Most chosen',
    ctaLabel: 'Start with this plan',
    finePrint:
      'All plans include bilingual storefronts, hosted infrastructure, responsive pages, and access to Gulf-first commerce tools. Free and Pro include Fawran plus cash on delivery. Pro+ and Max+ unlock SADAD, SkipCash, and Tap Payments. Prices exclude VAT.',
    tiers: [
      {
        id: 'free',
        name: 'FREE \u00b7 مجاني',
        tagline: 'Open a branded starter storefront.',
        price: '0',
        featured: false,
        featuresIntro: '',
        features: [
          '1 storefront',
          '10 products',
          '1 template',
          '25 orders per month',
          'Fawran + cash on delivery checkout',
          'Upgrade to unlock growth tools',
          'Souqna branding locked',
          'No custom domain, analytics, integrations, or AI',
        ],
      },
      {
        id: 'starter',
        name: 'PRO \u00b7 برو',
        tagline: 'Your core conversion plan.',
        price: '49',
        featured: false,
        featuresIntro: 'Everything in Free, plus:',
        features: [
          '2 storefronts',
          'Unlimited products',
          'Custom domain',
          '5 templates',
          'Remove branding',
          'Basic analytics',
          'WhatsApp integration',
          'Fawran + cash on delivery checkout',
          'Discount codes + SEO settings',
          'Email support',
        ],
      },
      {
        id: 'pro',
        name: 'PRO+ \u00b7 برو+',
        tagline: 'Scale your business with AI and automation.',
        price: '145',
        featured: true,
        featuresIntro: 'Everything in Pro, plus:',
        features: [
          '8 storefronts',
          'AI branding assets',
          'Marketing apps',
          'Payment providers: SADAD, SkipCash, Tap Payments',
          'Meta/TikTok integrations',
          'Team members + automation flows',
          'Premium templates and builder blocks',
          'Advanced analytics',
          'Priority support',
        ],
      },
      {
        id: 'atelier',
        name: 'MAX+ \u00b7 ماكس+',
        tagline: 'Run your business at scale.',
        price: '235',
        featured: false,
        featuresIntro: 'Everything in Pro+, plus:',
        features: [
          'Unlimited storefronts',
          'Team workspace',
          'Client permissions',
          'White-label tools',
          'API access',
          'All payment providers: SADAD, SkipCash, Tap Payments',
          'Advanced analytics AI',
          'Bulk operations',
          'Advanced SEO AI',
          'Early access features',
          'Dedicated support',
        ],
      },
    ],
  },

  begin: {
    eyebrow: 'open a storefront',
    title: 'Welcome to {italic}Souqna{/italic}.',
    titleItalic: 'Souqna',
    sub: 'A storefront in minutes. Pick a path below — we\u2019ll keep things short, and everything you set up here you can change later from your dashboard.',
    frameLeft: 'BUILT IN QATAR FOR THE GULF \u00b7 2026',
    frameRight: 'AI COMMERCE OS \u00b7 ARABIC + ENGLISH',
    progress: { step: 'Step', of: 'of' },
    nav: {
      back: 'Back',
      next: 'Continue',
      launch: 'Open your storefront',
      save: 'Save changes',
      skip: 'Skip for now',
    },
    pledge: 'Your storefront lives at souqna.qa — yours to share, edit and grow.',

    instagramImport: {
      invalidHandle: 'That does not look like an Instagram handle — letters, numbers, dots and underscores only.',
      rateLimited: 'Too many attempts — give it a minute and try again.',
      providerUnavailable: 'Instagram fetching is not available right now — you can upload product photos instead.',
      privateProfile: 'That profile is private, so we cannot read it. Upload product photos instead and the AI will take it from there.',
      fetchFailed: 'We could not read that profile. Check the handle, or upload product photos instead.',
      aiUnavailable: 'AI analysis is not available right now — you can still review and price your products manually.',
      importFailed: 'We could not import your products. Your storefront is live — add products from the dashboard.',
      uploadFailed: 'That image could not be uploaded. Use a PNG, JPG, or WebP under 5 MB.',
    },

    step1: {
      eyebrow: 'welcome',
      title: 'Tell us where you are.',
      sub: 'Two paths. Pick whichever feels closer — you can always change track later.',
      ownership: {
        label: '',
        options: [
          {
            id: 'have_business',
            label: 'I already run a business',
            helper: 'Bring a name, a product list, the trade you do today.',
          },
          {
            id: 'want_to_start',
            label: 'I\u2019m starting from scratch',
            helper: 'New idea, no products yet — we\u2019ll help you shape it.',
          },
        ],
      },
    },

    step2: {
      eyebrow: 'what kind',
      title: 'What kind of business is it?',
      sub: 'Pick the closest — this just tunes a few words on the page.',
      options: [
        { id: 'graphic_design', label: 'Graphic design', helper: 'Studio or freelance' },
        { id: 'clothing_store', label: 'Clothing store', helper: 'Retail or boutique' },
        { id: 'home_kitchen', label: 'Home kitchen', helper: 'Cloud kitchen or homecook' },
        { id: 'salon', label: 'Salon / barbershop', helper: 'Beauty, grooming, spa' },
        { id: 'cafe', label: 'Caf\u00e9 / restaurant', helper: 'Sit-down or takeaway' },
        { id: 'ecommerce', label: 'E-commerce', helper: 'Online store, any category' },
        { id: 'real_estate', label: 'Real estate', helper: 'Brokerage or office' },
        { id: 'photography', label: 'Photography', helper: 'Studio or events' },
        { id: 'tutoring', label: 'Tutoring / education', helper: 'Academic or skills' },
        { id: 'fitness', label: 'Fitness studio', helper: 'Gym, yoga, sports' },
        { id: 'perfume_oud', label: 'Perfume / oud', helper: 'Bakhoor, attar, scents' },
        { id: 'auto_detailing', label: 'Auto detailing', helper: 'Wash, polish, ceramic' },
        { id: 'events_weddings', label: 'Events / weddings', helper: 'Planning, decor, catering' },
        { id: 'agriculture', label: 'Farm / agriculture', helper: 'Produce, livestock, dairy' },
        { id: 'courier_delivery', label: 'Courier / delivery', helper: 'Doha-area runs' },
        { id: 'contracting', label: 'Contracting', helper: 'Construction or trades' },
        { id: 'art_gallery', label: 'Art gallery', helper: 'Exhibitions or sales' },
        { id: 'tailoring_abaya', label: 'Tailoring', helper: 'Abaya, thobe, alterations' },
        { id: 'fnb_brand', label: 'F&B brand', helper: 'Packaged food or beverage' },
        {
          id: 'something_else',
          label: 'Something else',
          helper: 'We\u2019ll figure it out together',
        },
      ],
    },

    step3: {
      eyebrow: 'name',
      title: 'What\u2019s your business called?',
      sub: 'We\u2019ll claim the address as you type. Anything goes — store, studio, kitchen, brand.',
      labels: {
        businessName: 'Business name',
        slug: 'Web address',
      },
      placeholders: {
        businessName: 'Al Sadd Kitchen',
      },
      helpers: {
        slug: 'Lowercase letters, numbers and dashes. 3–40 characters.',
        slugChecking: 'Checking availability\u2026',
        slugAvailable: 'Available',
        slugTaken: 'Taken — try',
        slugReserved: 'Reserved — please pick another.',
        slugInvalid: 'Use letters, numbers and dashes only.',
      },
      preview: 'Your storefront will live at',
    },

    step4: {
      eyebrow: 'template',
      title: 'Pick a template.',
      sub: 'Eleven starting points — every block resolves products from your own catalogue, never from demo placeholders. Rearrange or swap blocks freely once you\u2019re inside the dashboard.',
      options: [
        {
          id: 'atrium',
          label: 'Diwan · ديوان',
          helper:
            'Editorial boutique. Full-bleed hero, asymmetric product mosaic, captioned gallery, contact. The default — quiet and image-led, hospitable to almost any catalogue.',
        },
        {
          id: 'souqline',
          label: 'Souq · سوق',
          helper:
            'Dense market grid, RTL-first. Hero strip, twelve-tile product grid, banner, "new arrivals" list. Built for high-volume catalogues that breathe in Arabic.',
        },
        {
          id: 'kiosk',
          label: 'Workshop · ورشة',
          helper:
            'Single-product launch with a maker feel. Featured product (auto-resolves to the first active item), full-bleed hero, lookbook gallery, "more from us" sidebar. Terracotta palette, for capsule drops and small-batch makers.',
        },
        {
          id: 'lounge',
          label: 'Mono · مونو',
          helper:
            'Pure black and white. A hero, three menu surfaces pinned to categories, gallery, contact card with hours. The most graphic palette in the lineup — a true monochrome system.',
        },
        {
          id: 'studio',
          label: 'Laeb · لعب',
          helper:
            'Services and bookings, with a playful coral palette. Three placeholder service rows, a calendar, an "extras" product grid scoped to the services category. For bookable practices — kids classes, coaches, studios.',
        },
        {
          id: 'bazaar',
          label: 'Harvest · حصاد',
          helper:
            'Lookbook plus drops. Gallery hero, a `drop` block, featured-collection grids by category, banner, contact. Olive-brass palette — for brands that ship in seasonal editions.',
        },
        {
          id: 'vitrine',
          label: 'Zubara · الزبارة',
          helper:
            'Coastal editorial fashion. Banner cover, sub-hero, serif manifesto, four-up lookbook, asymmetric product mosaic, grouped collection list. Pearl-lagoon palette inspired by the Zubara coast — for ready-to-wear and ateliers that lead with imagery.',
        },
        {
          id: 'monoline',
          label: 'Wajba · وجبة',
          helper:
            'Refined hospitality. Centered hero, serif manifesto, a wide editorial image, divider, portfolio-style product grid, ghost CTA. Maroon-bone palette — for restaurants, private dining, and brands that lead with a meal.',
        },
        {
          id: 'harvest',
          label: 'Khor · الخور',
          helper:
            'Artisan marketplace, mangrove-green palette. Maker-led banner hero, "from the workshop" story, process gallery, lookbook product grid, grouped collection list, delivery banner. Made for things made by hand.',
        },
        {
          id: 'launchpad',
          label: 'Zikreet · زكريت',
          helper:
            'Tech and SaaS landing, dune-blush palette. Animated headline hero, "what you get" feature grid, a smaller animated cue mid-page, CTA, contact. Pro tier — uses the AnimatedText block, downgrades to a static headline on lower plans.',
        },
        {
          id: 'frame',
          label: 'Oryx · المها',
          helper:
            'Photography portfolio, dark fine-art palette. Kenburns image hero, sub-hero credit line, four-up gallery, featured edition, prints grid, commissions CTA. Pro tier — uses the AnimatedImage block, downgrades to a still on lower plans.',
        },
      ],
    },

    step5: {
      eyebrow: 'verify · optional',
      title: 'Have a Commercial Registration?',
      sub: 'Add it now and a small "Verified" chip appears on your storefront. Skip if you\u2019re just starting — you can add it later.',
      labels: {
        crNumber: 'CR number',
      },
      placeholders: {
        crNumber: '00000000',
      },
      helpers: {
        crNumber: 'We never display the number itself.',
      },
    },

    step6: {
      eyebrow: 'products · optional',
      title: 'Bring your products in.',
      sub: 'Drag in a CSV exported from Shopify, Sheets or your stock list. Headers like title, price, description, image_url, category, sku, in_stock and tags are recognised.',
      hint: 'Up to 200 rows per import. Skip and you\u2019ll add products manually from the dashboard.',
      pickFile: 'Choose a CSV file',
      change: 'Change file',
      uploading: 'Uploading\u2026',
      success: 'Imported {n} products.',
      partial: '{n} imported, {skipped} skipped (missing title).',
      failed: 'Import failed. Check the file and try again.',
    },

    step7: {
      eyebrow: 'launch',
      title: 'You\u2019re ready.',
      sub: 'We\u2019ll set up your storefront and drop you straight into the dashboard so you can start arranging it.',
      summary: {
        title: 'Quick summary',
        name: 'Name',
        slug: 'Address',
        template: 'Template',
        cr: 'Verification',
        products: 'Products imported',
        crNone: 'Skipped — add later',
        productsNone: 'None — add from dashboard',
      },
    },

    success: {
      title: 'Your storefront draft is ready.',
      body: 'Opening the builder so you can publish when it feels right\u2026',
    },
    error: {
      generic: 'Something didn\u2019t go through. Please try again, or email support@souqna.qa.',
      rateLimit: 'Too many submissions from this network. Please try again in a minute.',
      signInRequired: 'Please sign in to open a storefront.',
    },
    validation: {
      nameRequired: 'Please share your name.',
      bizRequired: 'Business name is required.',
      emailRequired: 'A real email — we send the edit link here.',
      ownershipRequired: 'Pick a path to continue.',
      experienceRequired: 'Pick the closest.',
      businessTypeRequired: 'Pick the closest kind.',
      marketRequired: 'Pick a market scale.',
      paymentsRequired: 'Pick the current state.',
      paletteRequired: 'Pick a palette.',
      templateRequired: 'Pick a template.',
      slugRequired: 'Pick a web address.',
    },
  },

  brief: {
    chrome: {
      eyebrow: 'a Souqna storefront for',
      sharedFrom: 'A storefront, hosted at',
      shareCta: 'Copy this link',
      shareDone: 'Copied.',
      expires: 'This page lives until',
    },
    notFound: {
      title: 'No storefront at this address.',
      body: 'Either the storefront expired, or the slug was never claimed. Begin a new one.',
      cta: 'Begin a storefront',
    },
  },

  dashboard: {
    eyebrow: 'owner dashboard',
    title: '{name}',
    sub: 'Add products, edit details, share the storefront. Sign in any time from your account.',
    notFound: 'No storefront at this address \u2014 it may have expired or never been claimed.',
    forbidden:
      'This storefront belongs to another founder. You can\u2019t edit it from this account.',
    startStore: 'Open a storefront',
    backToAccount: 'Back to your account',
    nav: {
      overview: 'Overview',
      products: 'Products',
      edit: 'Edit storefront',
      view: 'View live',
      back: 'Back to dashboard',
      account: 'Account',
    },
    overview: {
      stats: {
        products: 'products',
        active: 'live on storefront',
        drafts: 'drafts',
      },
      quickActions: {
        title: 'Quick actions',
        newProduct: 'Add a product',
        editStore: 'Edit storefront details',
        viewLive: 'View live storefront',
      },
      recent: 'Recent products',
      empty: {
        title: 'No products yet.',
        body: 'Add your first product to start filling the storefront.',
        cta: 'Add a product',
      },
    },
    edit: {
      eyebrow: 'profile',
      title: 'Storefront profile',
      sub: 'The practical bits — your business name, how customers reach you, and verification. Live at {url}.',
      saved: 'Saved \u2014 your storefront is live.',
      backToDashboard: 'Back to dashboard',
      viewLive: 'View live page',
      sections: {
        identity: 'Identity',
        contact: 'How customers reach you',
        verification: 'Verification',
      },
      labels: {
        businessName: 'Business name',
        tagline: 'Short tagline',
        phone: 'Phone',
        area: 'Area or address',
        hours: 'Hours',
        instagram: 'Instagram handle',
        logo: 'Logo',
        crNumber: 'Commercial Registration (CR)',
      },
      placeholders: {
        tagline: 'A serious kitchen, run from home in Al Sadd.',
        phone: '+974 5555 5555',
        area: 'Al Sadd, Doha',
        hours: 'Tue–Sun · 5–11pm',
        instagram: '@your-handle',
        crNumber: '00000000',
      },
      helpers: {
        crNumber:
          'When set, a small "Verified" chip appears on your storefront. The number is never shown publicly.',
        logo: 'PNG, JPG, WebP or SVG · max 50 MB',
      },
      save: 'Save changes',
      saving: 'Saving\u2026',
    },
  },

  products: {
    list: {
      title: 'Products',
      sub: 'Drag to reorder. Drafts stay hidden from the live storefront.',
      newCta: 'Add a product',
      empty: {
        title: 'No products yet.',
        body: 'Add the first one to bring the storefront to life.',
        cta: 'Add the first product',
      },
      columns: {
        title: 'Title',
        price: 'Price',
        status: 'Status',
        actions: '',
      },
      status: {
        active: 'Live',
        draft: 'Draft',
        sold_out: 'Sold out',
      },
      actions: {
        edit: 'Edit',
        delete: 'Delete',
        confirmDelete: 'Delete this product? This can\u2019t be undone.',
      },
    },
    form: {
      eyebrow: 'product',
      newTitle: 'Add a product',
      editTitle: 'Edit product',
      sub: 'Title is the only required field. Everything else is optional and editable later.',
      labels: {
        title: 'Title',
        description: 'Description',
        price: 'Price (QAR)',
        category: 'Category or section',
        eventAt: 'Date & time',
        image: 'Image',
        status: 'Status',
        customizable: 'Customizable',
        customizationLabel: 'Custom badge label',
      },
      placeholders: {
        title: 'Saffron rice with lamb',
        description: 'A short line about what makes this one yours.',
        price: 'e.g. 65',
        category: 'e.g. Mains',
        eventAt: 'YYYY-MM-DDTHH:MM',
      },
      helpers: {
        priceOptional: 'Leave blank for "on request".',
        category: 'Used to group rows on menu / service templates.',
        eventAt: 'For dated archetypes (events, calendar). Otherwise leave blank.',
        image: 'PNG, JPG or WebP \u00b7 max 50 MB.',
        customizable: 'Shows a customizable badge on storefront product cards.',
        customizationLabel: 'Leave blank to show "Customizable".',
      },
      status: {
        active: 'Live',
        draft: 'Draft',
        sold_out: 'Sold out',
      },
      submit: {
        create: 'Add product',
        save: 'Save changes',
      },
      cancel: 'Cancel',
      saved: 'Saved.',
      created: 'Product added.',
      error: {
        generic: 'Something didn\u2019t go through. Please try again.',
        titleRequired: 'A title, even rough.',
      },
    },
  },

  footer: {
    tagline:
      'Souqna is a bilingual commerce workspace designed in Doha for founders building Gulf storefronts.',
    columns: {
      atelier: {
        title: 'Platform',
        links: [
          { label: 'Workspace', href: '/#ai' },
          { label: 'Builder', href: '/#builder' },
          { label: 'Operations', href: '/#operations' },
          { label: 'Pricing', href: '/#pricing' },
        ],
      },
      doha: {
        title: 'Gulf',
        links: [
          { label: 'Souqy AI', href: '/#souqy' },
          { label: 'Apps', href: '/#apps' },
          { label: 'support@souqna.qa', href: 'mailto:support@souqna.qa' },
          { label: 'Instagram', href: '#' },
        ],
      },
      legal: {
        title: 'Company',
        links: [
          { label: 'Brand', href: '/brand' },
          { label: 'Docs', href: '/docs' },
          { label: 'Journal', href: '/journal' },
          { label: 'Begin', href: '/begin' },
          { label: 'Terms', href: '/docs#legal' },
          { label: 'Privacy', href: '/docs#legal' },
          { label: 'Refunds', href: '/refund' },
          { label: 'Shipping', href: '/shipping' },
        ],
      },
    },
    copyright: '\u00a9 2026 SOUQNA · QATAR',
    builtIn: 'BILINGUAL COMMERCE · DESIGNED IN DOHA',
    version: 'v1.0 · SPRING 2026',
    asideLabel: 'aligned',
  },

  brand: {
    eyebrow: 'brand book',
    title: 'Brand identity · spring 2026',
    sub: 'The visual identity \u2014 spring 2026',
    sections: {
      logo: {
        label: '01 · Primary logo',
        title: 'The wordmark, on three substrates.',
        lede: 'Bilingual by construction: Souqna and \u0633\u0648\u0642\u0646\u0627 hold equal weight, joined by a thin gold rule. Use the version with the highest contrast for the background.',
      },
      mark: {
        label: '02 · The arch',
        title: 'Mark geometry, scale, and family.',
        lede: 'The arch is Souqna\u2019s gateway: the point at which an idea crosses into a real, working business. Built on a 25-pixel unit grid.',
      },
      color: {
        label: '03 · Color',
        title: 'A palette rooted in the majlis.',
        lede: 'Sand carries every surface. Maroon holds emotion and identity. Gold earns its place at the call-to-action. Silver is the quiet tech signal. Charcoal, never pure black, does the typography.',
      },
      type: {
        label: '04 · Typography',
        title: 'Arabic and English, held in equal dignity.',
        lede: 'Thmanyah Sans carries UI and body copy; Thmanyah Serif Display carries high-impact headings; Thmanyah Serif Text supports longer editorial moments; JetBrains Mono handles meta and UI furniture.',
      },
      stationery: {
        label: '05 · Applied',
        title: 'Stationery and the business card.',
        lede: 'Silver foil on light maroon for the card; a calm letterhead on sand; a compliments slip on charcoal. Every piece carries the arch \u2014 quietly.',
      },
      og: {
        label: '06 · Digital',
        title: 'Open-graph card.',
        lede: 'The default social share. 1200\u00d7630. Type does the work; the arch watermarks the right margin.',
      },
    },
    captions: {
      onSand: 'ON SAND \u00b7 #E8DCC4',
      onMaroon: 'ON MAROON \u00b7 #8B3A3A',
      onCharcoal: 'ON CHARCOAL \u00b7 #2A2A2A',
      geometry: 'GEOMETRY \u00b7 25PX UNIT',
      wordmarkScale: 'WORDMARK \u00b7 SCALE',
      markFamily: 'MARK \u00b7 FAMILY',
      palette: 'CORE PALETTE',
      typePairing: 'BILINGUAL PAIRING',
      businessCard: 'BUSINESS CARD \u00b7 85\u00d755mm \u00b7 SILVER FOIL ON MAROON',
      stationerySet: 'STATIONERY \u00b7 LETTERHEAD + COMPLIMENTS + INVOICE BAND',
      openGraph: 'OPEN GRAPH \u00b7 1200\u00d7630',
    },
  },

  langSwitch: {
    label: 'Language',
    toEnglish: 'English',
    toArabic: 'العربية',
  },

  builder: {
    empty: {
      pageTitle: 'Online store',
      pageSubtitle: 'The builder edits a specific storefront. Set one up to start.',
      eyebrow: 'Get started',
      title: 'Create your store first',
      body: 'Pick a template, fill in your business details, and Souqna seeds a complete storefront with rich starter content.',
      cta: 'Create your store',
    },
    orientation: {
      message:
        'Rotate your phone for the full editor — portrait works for quick edits but landscape gives every control room to breathe.',
      dismiss: 'Dismiss',
    },
    media: {
      uploading: 'Uploading…',
      dropOrBrowse: 'Drop image · or click to browse',
      formats: 'PNG · JPG · WEBP · ≤ 1 MB',
      remove: 'Remove',
      pickGif: '◈ Pick a GIF',
      uploadFailed: 'Upload failed. Try a smaller image (≤1MB) in PNG/JPG/WEBP.',
    },
    publish: {
      saving: 'Saving…',
      saveFailed: 'Save failed',
      saved: 'Saved',
      published: 'Published',
      draft: 'Draft',
      livePreviewDraft: 'Live preview · draft',
      publish: 'Publish',
      discardConfirm: 'Discard draft and revert to the published version?',
      discardDraft: 'Discard draft',
    },
    souqyLiveHint: {
      message:
        'Your AI-built storefront renders on your live subdomain. This canvas edits JSON blocks—the preview iframe shows your draft layout, not the Souqy artifact.',
      openLive: 'Open live site',
      dismiss: 'Dismiss',
    },
    rail: {
      pages: 'Pages',
      site: 'Site',
      block: 'Block',
      library: 'Library',
      outline: 'Outline',
      apps: 'Apps',
    },
    topbar: {
      closePanels: 'Close panels',
      toggleLibrary: 'Toggle library / outline panel',
      backToAccount: 'Back to account',
      account: 'Account',
      openNavigation: 'Open navigation',
      navigate: 'Navigate',
      language: 'Builder language',
      replayTour: 'Replay builder tour',
      commandPalette: 'Open command palette (⌘K)',
      undo: 'Undo (⌘Z)',
      redo: 'Redo (⌘⇧Z)',
      publish: 'Publish',
      publishing: 'Publishing…',
      checkingLive: 'Going live…',
      live: 'Live',
      liveFailed: 'Live check failed',
      toggleInspector: 'Toggle inspector',
      moreActions: 'More actions',
      viewLive: 'View live ↗',
      products: 'Products',
      storefrontProfile: 'Storefront profile',
      resetTemplate: 'Reset to template defaults',
      discardDraft: 'Discard draft',
      needsPublish: 'Needs to be published',
      device: {
        label: 'Preview device',
        desktop: 'Desktop · responsive',
        tablet: 'Tablet · 820px',
        mobile: 'Mobile · 390px',
        responsive: 'Responsive',
      },
    },
    nav: {
      aria: 'Builder navigation',
      close: 'Close menu',
      brand: '◈ Souqna',
      builder: 'Builder',
      builderDesc: 'Drag, edit, publish — current page',
      products: 'Products',
      productsDesc: 'Catalog, pricing, photos',
      profile: 'Storefront profile',
      profileDesc: 'Tagline, contact, logo',
      live: 'View live ↗',
      liveDesc: 'Open the published site',
      allStores: 'All my storefronts',
      allStoresDesc: 'Switch business or sign out',
      reset: 'Reset to template defaults',
      resetDesc: 'Snap back to the blocks you picked at /begin',
      discard: 'Discard draft',
      discardDesc: 'Roll back unpublished edits',
    },
    canvas: {
      editing: 'Editing',
      home: 'home',
      responsive: 'responsive',
      frame: 'frame',
    },
    blockLabels: {
      hero: 'Hero',
      banner: 'Banner',
      text: 'Text',
      image: 'Image',
      gallery: 'Gallery',
      productGrid: 'Product grid',
      productList: 'Product list',
      featuredProduct: 'Featured product',
      serviceList: 'Service list',
      menu: 'Menu',
      calendar: 'Calendar',
      contactCard: 'Contact card',
      inquireCta: 'Inquire CTA',
      spacer: 'Spacer',
      divider: 'Divider',
      drop: 'Drop',
      animatedText: 'Animated text',
      animatedImage: 'Animated image',
      productCardStack: 'Product stack',
      tiltImage: 'Tilt image',
      spotlightCard: 'Spotlight card',
      productPromoCard: 'Promo product',
      mawid: 'Mawid · countdown',
      taqim: 'Taqim · bundle',
      depthShowcase: 'Depth showcase',
      auroraRibbon: 'Aurora ribbon',
      curvedLoop: 'Curved loop',
      showcase1: 'Case switcher',
      showcase2: 'Image marquee',
      showcase3: '3D story wheel',
      showcase4: 'Filter portfolio',
      showcase5: 'Tabbed image rail',
      ecommerce1: 'Product gallery',
      ecommerce2: 'Shop filters',
      ecommerce3: 'Color detail',
      ecommerce4: 'Drop product',
      ecommerce5: 'Editorial shelf',
      ecommerce6: 'Category shop',
      ecommerce7: 'Category tiles',
      ecommerce9: 'Quick-add grid',
    },
    library: {
      groups: {
        layout: 'Layout',
        products: 'Products',
        plugins: 'Souqna plugins',
        contact: 'Contact',
        animation: 'Animation',
        spacing: 'Spacing',
      },
      items: {
        hero: { label: 'Hero', hint: 'Intro' },
        banner: { label: 'Banner', hint: 'Wide image' },
        text: { label: 'Text', hint: 'Copy' },
        image: { label: 'Image', hint: 'Picture' },
        gallery: { label: 'Gallery', hint: 'Grid' },
        productGrid: { label: 'Product grid', hint: 'Cards' },
        productList: { label: 'Product list', hint: 'List' },
        featuredProduct: { label: 'Featured', hint: 'Feature' },
        productCardStack: { label: 'Card stack', hint: 'Stack' },
        productPromoCard: { label: 'Promo card', hint: 'Promo' },
        ecommerce1: { label: 'Product gallery', hint: 'Gallery' },
        ecommerce2: { label: 'Shop filters', hint: 'Filters' },
        ecommerce3: { label: 'Color detail', hint: 'Detail' },
        ecommerce4: { label: 'Drop product', hint: 'Drop' },
        ecommerce5: { label: 'Editorial shelf', hint: 'Shelf' },
        ecommerce6: { label: 'Category shop', hint: 'Categories' },
        ecommerce7: { label: 'Category tiles', hint: 'Tiles' },
        ecommerce9: { label: 'Quick-add grid', hint: 'Quick add' },
        menu: { label: 'Menu', hint: 'Prices' },
        serviceList: { label: 'Services', hint: 'Cards' },
        calendar: { label: 'Calendar', hint: 'Dates' },
        drop: { label: 'Drop (Drop Manager)', hint: 'Timed launch' },
        taqim: { label: 'Bundle (Taqim)', hint: 'Bundle' },
        mawid: { label: 'Countdown (Mawid)', hint: 'Timer' },
        contactCard: { label: 'Contact', hint: 'Info' },
        inquireCta: { label: 'Inquire CTA', hint: 'Button' },
        animatedText: { label: 'Animated text', hint: 'Motion' },
        animatedImage: { label: 'Animated image', hint: 'Motion' },
        tiltImage: { label: 'Tilt image', hint: 'Tilt' },
        spotlightCard: { label: 'Spotlight card', hint: 'Spotlight' },
        depthShowcase: { label: 'Depth showcase', hint: 'Depth' },
        auroraRibbon: { label: 'Aurora ribbon', hint: 'Ribbon' },
        curvedLoop: { label: 'Curved loop', hint: 'Loop' },
        showcase1: { label: 'Case switcher', hint: 'Switcher' },
        showcase2: { label: 'Image marquee', hint: 'Marquee' },
        showcase3: { label: '3D story wheel', hint: '3D wheel' },
        showcase4: { label: 'Filter portfolio', hint: 'Portfolio' },
        showcase5: { label: 'Tabbed image rail', hint: 'Tabs' },
        spacer: { label: 'Spacer', hint: 'Space' },
        divider: { label: 'Divider', hint: 'Rule' },
      },
    },
    outline: {
      aria: 'Dashboard sections',
      dragHandle: 'Drag handle',
      moveUp: 'Move up',
      moveDown: 'Move down',
      duplicate: 'Duplicate',
      delete: 'Delete',
      dropsAtEnd: 'Drops at the end',
      dropFirst: 'Drop to add as the first block',
      dropFromLibrary: 'Drop a block here from the Library tab.',
    },
    recommendations: {
      aria: 'Builder recommendations',
      heading: 'Recommendations',
      sections: 'sections',
      premiumRefreshTitle: 'Premium refresh',
      premiumRefreshBody:
        'Replace this draft with the newest premium version of the selected template.',
      refresh: 'Refresh',
      applyMotionTitle: 'Apply premium motion',
      applyMotionBody: 'This block can use the template motion surface.',
      premiumIncluded: 'Premium visuals are included for every Souqna storefront.',
      apply: 'Apply',
      addMotionTitle: 'Add a motion section',
      addMotionBody:
        'A kinetic headline or animated image gives this page a premium first-scroll moment.',
      addAnimatedText: 'Add animated text',
      showCatalogueTitle: 'Show the catalogue',
      showCatalogueBody:
        'Add a product grid so buyers can scan real items instead of reading the page like a brochure.',
      addGrid: 'Add grid',
      addCtaTitle: 'Add a clear next step',
      addCtaBody:
        'Premium pages still need one obvious buyer action: inquire, book, call, or visit.',
      addCta: 'Add CTA',
      tuneSystemTitle: 'Tune the whole system',
      tuneSystemBody:
        'Template, palette, SEO, and page background live in Site. Use it when the page feels close but not fully branded.',
      openSite: 'Open Site',
    },
    selectionToolbar: {
      actionsAria: 'actions',
      exitSouqy: 'Exit Souqy edit',
      moveUp: 'Move up',
      moveDown: 'Move down',
      duplicate: 'Duplicate',
      edit: 'Edit',
      delete: 'Delete',
      askSouqy: 'Edit with Souqy',
      askSouqyTitle: 'Edit with Souqy (AI)',
      upgradeSouqy: 'Upgrade to edit with Souqy',
      upgradeSouqyTitle: 'Upgrade to unlock Souqy AI edits',
      promptLabelPrefix: 'Tell Souqy what to change about',
      promptLabelSuffix: 'block',
      placeholder: 'Tell Souqy what to change…',
      errorPlaceholder: 'Try a different prompt',
      editing: 'Editing…',
      retry: 'Retry',
      retryAria: 'Retry Souqy edit',
      dismiss: 'Dismiss',
      dismissAria: 'Dismiss Souqy',
      send: 'Send to Souqy',
      sendTitle: 'Send (Enter)',
      suggestionsAria: 'Souqy prompt suggestions',
      upgradeMessage: 'Souqy AI edits are a Pro upgrade.',
      upgrade: 'Upgrade',
      fallbackError: 'Souqy could not edit this block.',
      suggestions: [
        { label: 'Darker', prompt: 'Make this block darker and more premium', lang: 'en' },
        { label: 'Center', prompt: 'Center the copy and give it more breathing room', lang: 'en' },
        {
          label: 'Headline',
          prompt: 'Make the headline say "New season, made in Doha"',
          lang: 'en',
        },
        { label: 'Gold', prompt: 'Use a gold accent and stronger contrast', lang: 'en' },
        { label: 'Mobile', prompt: 'Make this section compact for mobile', lang: 'en' },
        { label: 'Glow', prompt: 'Give this block a pro aurora glow', lang: 'en' },
        { label: 'CTA', prompt: 'Change the button label to "Shop now"', lang: 'en' },
        { label: 'Hide', prompt: 'Hide this block for now', lang: 'en' },
      ],
    },
    inspector: {
      emptyTitle: 'Page',
      emptyBody: 'Select a block in the Outline (or click one in the preview) to edit its content.',
      emptySiteHint: 'Switch to the Site tab to edit page background, template, and SEO.',
      tabs: { content: 'Content', style: 'Style' },
      labels: {
        Page: 'Page',
        Site: 'Site',
        Eyebrow: 'Eyebrow',
        Title: 'Title',
        Tagline: 'Tagline',
        Heading: 'Heading',
        Body: 'Body',
        Kicker: 'Kicker',
        Subtitle: 'Subtitle',
        Description: 'Description',
        Category: 'Category',
        Products: 'Products',
        Image: 'Image',
        Images: 'Images',
        Link: 'Link',
        Label: 'Label',
        Button: 'Button',
        'Alt text': 'Alt text',
        Caption: 'Caption',
        'CTA label': 'CTA label',
        'CTA link': 'CTA link',
        Layout: 'Layout',
        Alignment: 'Alignment',
        Style: 'Style',
        Content: 'Content',
        'Page background': 'Page background',
        'Store policies': 'Store policies',
        'Policy layout': 'Policy layout',
        'Terms Of Service': 'Terms Of Service',
        Privacy: 'Privacy',
        Refunds: 'Refunds',
        'Terms for orders, payments, delivery, and custom work.':
          'Terms for orders, payments, delivery, and custom work.',
        'How customer details are used for orders and support.':
          'How customer details are used for orders and support.',
        'How refunds, exchanges, and cancellations are handled.':
          'How refunds, exchanges, and cancellations are handled.',
        'Pattern library': 'Pattern library',
        'Background motion': 'Background motion',
        'Cursor effects': 'Cursor effects',
        Advanced: 'Advanced',
        'Theme behaviour': 'Theme behaviour',
        'Heading weight': 'Heading weight',
        'Section spacing': 'Section spacing',
        SEO: 'SEO',
        'Social share image (1200×630)': 'Social share image (1200×630)',
        Template: 'Template',
        'Current template': 'Current template',
        'Showing real previews with your products.':
          'Showing real previews with your products.',
        'Browse all templates': 'Browse all templates',
        'Switch template': 'Switch template',
        'Paid template · upgrade required': 'Paid template · upgrade required',
        Close: 'Close',
        'See plans': 'See plans',
        'Upgrade · talk to us': 'Upgrade · talk to us',
        'Replace template': 'Replace template',
        Cancel: 'Cancel',
        'Switching…': 'Switching…',
        'Use palette ground': 'Use palette ground',
        'Accent colour': 'Accent colour',
        'Add to cart button': 'Add to cart button',
        Align: 'Align',
        'Align items (cross axis)': 'Align items (cross axis)',
        'All tab': 'All tab',
        'All tab source': 'All tab source',
        'Anchor product': 'Anchor product',
        Area: 'Area',
        Aspect: 'Aspect',
        'Aspect ratio': 'Aspect ratio',
        'Auto-generate options': 'Auto-generate options',
        'Back cards': 'Back cards',
        Background: 'Background',
        Backgrounds: 'Backgrounds',
        'Badge EN': 'Badge EN',
        Brightness: 'Brightness',
        'Builder bundle': 'Builder bundle',
        'Bundle id (empty = Builder controlled)': 'Bundle id (empty = Builder controlled)',
        'Bundle price QAR': 'Bundle price QAR',
        'Buyer chooses option': 'Buyer chooses option',
        CTA: 'CTA',
        'CTA behavior': 'CTA behavior',
        'Card treatment': 'Card treatment',
        'Carousel cards': 'Carousel cards',
        'Carousel images': 'Carousel images',
        'Cart CTA mode': 'Cart CTA mode',
        Categories: 'Categories',
        'Click behavior': 'Click behavior',
        'Color scheme': 'Color scheme',
        'Curated tabs': 'Curated tabs',
        Curve: 'Curve',
        'Date · bottom line': 'Date · bottom line',
        'Date · top line': 'Date · top line',
        'Delay (ms)': 'Delay (ms)',
        Density: 'Density',
        'Design variant': 'Design style',
        Destination: 'Destination',
        Direction: 'Direction',
        'Discount mode': 'Discount mode',
        Display: 'Display',
        Draggable: 'Draggable',
        Effect: 'Effect',
        Emphasis: 'Emphasis',
        'Empty tab behavior': 'Empty tab behavior',
        'Event id (optional · from Apps → Mawid)': 'Event id (optional · from Apps → Mawid)',
        'Filter by category': 'Filter by category',
        'Filterable grid': 'Filterable grid',
        'Filters enabled': 'Filters enabled',
        'Fixed discount QAR': 'Fixed discount QAR',
        'Gallery layout': 'Gallery layout',
        Gap: 'Gap',
        'Group by category': 'Group by category',
        'Group label AR': 'Group label AR',
        'Group label EN': 'Group label EN',
        'Heading override': 'Heading override',
        Headline: 'Headline',
        Height: 'Height',
        'Height (px)': 'Height (px)',
        'Hide empty options': 'Hide empty options',
        'Hide unavailable': 'Hide unavailable',
        Hours: 'Hours',
        Icon: 'Icon',
        Instagram: 'Instagram',
        Intensity: 'Intensity',
        Items: 'Items',
        'Justify (main axis)': 'Justify (main axis)',
        'Label AR': 'Label AR',
        'Label EN': 'Label EN',
        'Launch time': 'Launch time',
        Logo: 'Logo',
        Loop: 'Loop',
        'Loop text': 'Loop text',
        Monogram: 'Monogram',
        Motion: 'Motion',
        Navigation: 'Navigation',
        Note: 'Note',
        Offer: 'Offer',
        'Offer label': 'Offer label',
        Overlay: 'Overlay',
        Pattern: 'Pattern',
        Patterns: 'Patterns',
        'Per-product add buttons': 'Per-product add buttons',
        'Percent off': 'Percent off',
        Phone: 'Phone',
        Projects: 'Projects',
        'Required item': 'Required item',
        Scrim: 'Scrim',
        'Scroll to': 'Scroll to',
        'Selected product': 'Selected product',
        Services: 'Services',
        'Show Instagram': 'Show Instagram',
        'Show area': 'Show area',
        'Show category / brand': 'Show category / brand',
        'Show date badge': 'Show date badge',
        'Show description': 'Show description',
        'Show hours': 'Show hours',
        'Show images': 'Show images',
        'Show inquire button': 'Show inquire button',
        'Show monogram': 'Show monogram',
        'Show phone': 'Show phone',
        'Show prices': 'Show prices',
        'Show savings': 'Show savings',
        Size: 'Size',
        Sort: 'Sort',
        Source: 'Source',
        Spacing: 'Spacing',
        Speed: 'Speed',
        Sticky: 'Sticky',
        Subhead: 'Subhead',
        Subheading: 'Subheading',
        Surface: 'Surface',
        'Switcher items': 'Switcher items',
        Tabs: 'Tabs',
        'Tag / collection': 'Tag / collection',
        'Tag position': 'Tag position',
        'Tag reveal': 'Tag reveal',
        Tags: 'Tags',
        Text: 'Text',
        'Text align': 'Text align',
        'Text colour': 'Text colour',
        'Text motion': 'Text motion',
        'Tile tabs': 'Tile tabs',
        'Tilt direction': 'Tilt direction',
        'Title AR': 'Title AR',
        'Title EN': 'Title EN',
        Tone: 'Tone',
        'Trust metrics': 'Trust metrics',
        Value: 'Value',
        Variant: 'Variant',
        'Visual category tiles': 'Visual category tiles',
        Width: 'Width',
        Wrap: 'Wrap',
      },
      actions: {
        moveUp: 'Move up',
        moveDown: 'Move down',
        duplicate: 'Duplicate',
        duplicateShortcut: 'Duplicate (⌘D)',
        delete: 'Delete',
      },
      options: {
        Auto: 'Auto',
        Light: 'Light',
        Dark: 'Dark',
        Regular: 'Regular',
        Medium: 'Medium',
        Semibold: 'Semibold',
        'All at once': 'All at once',
        Columns: 'Columns',
        Tight: 'Tight',
        Comfort: 'Comfort',
        Spacious: 'Spacious',
        None: 'None',
        Start: 'Start',
        Center: 'Center',
        End: 'End',
        Classic: 'Classic',
        Centered: 'Centered',
        Inline: 'Inline',
        Banner: 'Banner',
        Cards: 'Cards',
        Minimal: 'Minimal',
        Lookbook: 'Lookbook',
        Split: 'Split',
        Stacked: 'Stacked',
        Active: 'Active',
        Paused: 'Paused',
        Short: 'Short',
        Tall: 'Tall',
        Hide: 'Hide',
        Default: 'Default',
        Custom: 'Custom',
        Image: 'Image',
        Pattern: 'Pattern',
        Soft: 'Soft',
        Strong: 'Strong',
        Stripes: 'Stripes',
        Dots: 'Dots',
        Grid: 'Grid',
        Left: 'Left',
        Right: 'Right',
        'Lift only': 'Lift only',
        Subtle: 'Subtle',
        Med: 'Med',
        Narrow: 'Narrow',
        Wide: 'Wide',
        Full: 'Full',
        'Top start': 'Top start',
        'Top end': 'Top end',
        Always: 'Always',
        'On hover': 'On hover',
        One: 'One',
        Two: 'Two',
        Sm: 'Sm',
        Md: 'Md',
        Lg: 'Lg',
        XL: 'XL',
        Compact: 'Compact',
        Standard: 'Standard',
        Hero: 'Hero',
        Accent: 'Accent',
        Ink: 'Ink',
        Gold: 'Gold',
        Muted: 'Muted',
        Reveal: 'Reveal',
        Kinetic: 'Kinetic',
        Wave: 'Wave',
        Typewriter: 'Typewriter',
        Glitch: 'Glitch',
        Slow: 'Slow',
        Fast: 'Fast',
        Parallax: 'Parallax',
        'Ken Burns': 'Ken Burns',
        Tilt: 'Tilt',
        Boxed: 'Boxed',
        Stack: 'Stack',
        Carousel: 'Carousel',
        Block: 'Block',
        Flex: 'Flex',
        Hidden: 'Hidden',
        Row: 'Row',
        Column: 'Column',
        'Row reverse': 'Row reverse',
        'Column reverse': 'Column reverse',
        'No wrap': 'No wrap',
        Wrap: 'Wrap',
        'Wrap reverse': 'Wrap reverse',
        'Space between': 'Space between',
        'Space around': 'Space around',
        'Space evenly': 'Space evenly',
        Stretch: 'Stretch',
        Baseline: 'Baseline',
        Sand: 'Sand',
        Maroon: 'Maroon',
        Charcoal: 'Charcoal',
        Balanced: 'Balanced',
        Editorial: 'Editorial',
        Sidebar: 'Sidebar',
        Topbar: 'Topbar',
        'Add all': 'Add all',
        Selected: 'Selected',
        'New tab': 'New tab',
        'All products': 'All products',
        'Manual selection': 'Manual selection',
        Category: 'Category',
        'Tag / collection': 'Tag / collection',
        'Latest products': 'Latest products',
        'Choose category': 'Choose category',
        'Future-ready tag or collection': 'Future-ready tag or collection',
        Manual: 'Manual',
        Newest: 'Newest',
        'Price low to high': 'Price low to high',
        'Price high to low': 'Price high to low',
        'Title A-Z': 'Title A-Z',
        'Add products from the founder dashboard, then pick them here for this section.':
          'Add products from the founder dashboard, then pick them here for this section.',
        'Search products': 'Search products',
        Up: 'Up',
        Down: 'Down',
        Remove: 'Remove',
        'No manual products selected yet.': 'No manual products selected yet.',
        Add: 'Add',
        'Select active': 'Select active',
        Clear: 'Clear',
        Availability: 'Availability',
        'Remove group': 'Remove group',
        '+ Add filter group': '+ Add filter group',
        'Remove option': 'Remove option',
        '+ Add option': '+ Add option',
        'Direct add': 'Direct add',
        'Quick view': 'Quick view',
        'Product page': 'Product page',
        'Combine tab products': 'Combine tab products',
        'All store products': 'All store products',
        'Manual All products': 'Manual All products',
        'Show empty state': 'Show empty state',
        'Hide empty tab': 'Hide empty tab',
        'Fallback to all products': 'Fallback to all products',
        'Tab slug': 'Tab slug',
        'Remove tab': 'Remove tab',
        '+ Add tab': '+ Add tab',
        'Filter products below': 'Filter products below',
        'Scroll to product grid': 'Scroll to product grid',
        'Open collection drawer': 'Open collection drawer',
        'Dark gradient': 'Dark gradient',
        'Light overlay': 'Light overlay',
        'Minimal text': 'Minimal text',
        Framed: 'Framed',
        'Eyebrow EN': 'Eyebrow EN',
        'Eyebrow AR': 'Eyebrow AR',
        'Manual products': 'Manual products',
        'Store page': 'Store page',
        'Page slug': 'Page slug',
        'Remove tile': 'Remove tile',
        '+ Add tile': '+ Add tile',
        'Bundle product': 'Bundle product',
        'Default option, if needed': 'Default option, if needed',
        'Product badge EN': 'Product badge EN',
        'Product badge AR': 'Product badge AR',
        'Auto total': 'Auto total',
        'Percent discount': 'Percent discount',
        'Fixed amount discount': 'Fixed amount discount',
        'Fixed bundle price': 'Fixed bundle price',
        'Display-only badge': 'Display-only badge',
        Shield: 'Shield',
        Truck: 'Truck',
        Boxes: 'Boxes',
        Heart: 'Heart',
        '+ Add metric': '+ Add metric',
        'Uses the real storefront logo, store name, system pages, custom pages, policy links, and cart route.':
          'Uses the real storefront logo, store name, system pages, custom pages, policy links, and cart route.',
        'All categories': 'All categories',
        'Pick a product': 'Pick a product',
        Uncategorised: 'Uncategorised',
        'External link': 'External link',
        Static: 'Static',
        Lines: 'Lines',
        Texture: 'Texture',
        Depth: 'Depth',
        Glass: 'Glass',
        Rays: 'Rays',
        Metal: 'Metal',
        Mosaic: 'Mosaic',
        'Use the normal section surface.': 'Use the normal section surface.',
        'Slow fabric-like motion.': 'Slow fabric-like motion.',
        'Soft moving grain.': 'Soft moving grain.',
        'Blurred ambient glow.': 'Blurred ambient glow.',
        'Bright liquid glass.': 'Bright liquid glass.',
        'Subtle falling light.': 'Subtle falling light.',
        'Measured editorial stripes.': 'Measured editorial stripes.',
        'Small dotted texture.': 'Small dotted texture.',
        'Dimensional metallic motion.': 'Dimensional metallic motion.',
        'Pattern category': 'Pattern category',
        'Background patterns': 'Background patterns',
        All: 'All',
        'Clear pattern': 'Clear pattern',
        Gradient: 'Gradient',
        Geometric: 'Geometric',
        Mesh: 'Mesh',
        Noise: 'Noise',
        'Soft dots': 'Soft dots',
        'Bold dots': 'Bold dots',
        'Fine grid': 'Fine grid',
        'Graph paper': 'Graph paper',
        'Diagonal stripes': 'Diagonal stripes',
        Pinstripe: 'Pinstripe',
        Checker: 'Checker',
        Isometric: 'Isometric',
        Blueprint: 'Blueprint',
        'Paper fiber': 'Paper fiber',
        'Subtle noise': 'Subtle noise',
        'Warm mesh': 'Warm mesh',
        'Cool mesh': 'Cool mesh',
        'Conic burst': 'Conic burst',
        Sunset: 'Sunset',
        'Ink wash': 'Ink wash',
        'Grid fade': 'Grid fade',
        'Dot mask': 'Dot mask',
        'Card corners': 'Card corners',
        Spotlight: 'Spotlight',
        'Diagonal grid': 'Diagonal grid',
        Aurora: 'Aurora',
        Magnetic: 'Magnetic',
        Neon: 'Neon',
        Silk: 'Silk',
        Grain: 'Grain',
        Halftone: 'Halftone',
        Metallic: 'Metallic',
        Bars: 'Bars',
        Chroma: 'Chroma',
        'Clean, neutral. The default.': 'Clean, neutral. The default.',
        'Animated gradient mesh backdrop.': 'Animated gradient mesh backdrop.',
        'Cursor-following parallax tilt.': 'Cursor-following parallax tilt.',
        'Glowing gradient frame.': 'Glowing gradient frame.',
        'Premium silk-wave surface.': 'Premium silk-wave surface.',
        'Soft grain-wave editorial motion.': 'Soft grain-wave editorial motion.',
        'Animated dot-wave texture.': 'Animated dot-wave texture.',
        'Premium swirl and sheen surface.': 'Premium swirl and sheen surface.',
        'Moving gradient bar system.': 'Moving gradient bar system.',
        'Depth card with chromatic edge.': 'Depth card with chromatic edge.',
        'Uses the storefront logo (or auto monogram if none uploaded).':
          'Uses the storefront logo (or auto monogram if none uploaded).',
        'Or letters (1-4)': 'Or letters (1-4)',
        'An uploaded image takes precedence over letters.':
          'An uploaded image takes precedence over letters.',
        'Uses the auto type-glyph for your business category.':
          'Uses the auto type-glyph for your business category.',
        'On the live storefront the button smooth-scrolls to that block. The Link field is ignored while this is set. In this preview, clicking selects the block instead.':
          'On the live storefront the button smooth-scrolls to that block. The Link field is ignored while this is set. In this preview, clicking selects the block instead.',
      },
    },
  },
} as const;
