export const ARAMEX_ACCOUNT_LINKS = [
  {
    id: 'business-account',
    label: 'Open a business account',
    labelAr: 'فتح حساب أعمال',
    href: 'https://www.aramex.com/sign-up?business=',
  },
  {
    id: 'sign-in',
    label: 'Sign in to Aramex',
    labelAr: 'تسجيل الدخول إلى أرامكس',
    href: 'https://www.aramex.com/qa/en/login',
  },
  {
    id: 'account-help',
    label: 'Find account number / request PIN',
    labelAr: 'العثور على رقم الحساب أو طلب الرقم السري',
    href: 'https://www.aramex.com/help/Content/Topics/Dashboard/Accounts/Add_a_linked_account.htm',
  },
  {
    id: 'api-docs',
    label: 'Open Aramex API documentation',
    labelAr: 'فتح توثيق واجهة أرامكس البرمجية',
    href: 'https://www.aramex.com/qa/en/developers-solution-center/aramex-apis',
  },
] as const;

export const ARAMEX_SETTINGS_COPY = {
  en: {
    eyebrow: 'Customise',
    title: 'Aramex shipping',
    description:
      'Connect the Aramex business account for this storefront. Souqna keeps its password and PIN encrypted, then selects the domestic or international parcel service from each destination country.',
    save: 'Save changes',
    testConnection: 'Test connection',
    testing: 'Testing…',
    connected: 'Aramex account connected.',
    account: 'Account',
    accountHelpLabel: 'Aramex account help',
    accountHelp:
      'Need your Aramex credentials? Open a business account first. Existing merchants can sign in, link their corporate account, or request the account PIN from Aramex.',
    credentialLinks: 'Aramex credential links',
    username: 'Username',
    accountNumber: 'Account number',
    entity: 'Entity',
    entityHint: 'Origin city code, e.g. DOH for Doha.',
    country: 'Country',
    countryHint: 'ISO country code of your account.',
    updateCredentials:
      'Update password / PIN (leave unchecked to keep what’s already saved)',
    credentialsRequired: 'Password and PIN are required to finish the first connection',
    password: 'Password',
    accountPin: 'Account PIN',
    service: 'Service',
    serviceDescription:
      'Souqna uses the domestic service when the destination matches the account country; every other destination uses the international service.',
    domesticService: 'Domestic parcel service',
    domesticHint: 'Usually OND; confirm the code enabled on your account.',
    internationalService: 'International parcel service',
    internationalHint: 'PPX is Priority Parcel Express for cross-border goods.',
    pickupAddress: 'Pickup address',
    addressLine1: 'Address line 1',
    addressLine2: 'Address line 2 (optional)',
    city: 'City',
    countryCode: 'Country code',
    postalCode: 'Postal code',
    contactName: 'Contact name',
    contactPhone: 'Contact phone',
    contactEmail: 'Contact email',
    defaultParcel: 'Default parcel',
    weight: 'Weight (kg)',
    length: 'L (cm)',
    width: 'W (cm)',
    height: 'H (cm)',
  },
  ar: {
    eyebrow: 'تخصيص',
    title: 'الشحن مع أرامكس',
    description:
      'اربط حساب أرامكس التجاري بهذا المتجر. تحفظ سوقنا كلمة المرور والرقم السري للحساب بشكل مشفّر، ثم تختار خدمة الطرود المحلية أو الدولية تلقائياً حسب بلد الوجهة.',
    save: 'حفظ التغييرات',
    testConnection: 'اختبار الاتصال',
    testing: 'جارٍ الاختبار…',
    connected: 'تم الاتصال بحساب أرامكس.',
    account: 'الحساب',
    accountHelpLabel: 'مساعدة حساب أرامكس',
    accountHelp:
      'هل تحتاج بيانات حساب أرامكس؟ افتح حساب أعمال أولاً. إذا كان لديك حساب، سجّل الدخول ثم اربط الحساب التجاري أو اطلب الرقم السري للحساب من أرامكس.',
    credentialLinks: 'روابط بيانات حساب أرامكس',
    username: 'اسم المستخدم',
    accountNumber: 'رقم الحساب',
    entity: 'رمز الجهة',
    entityHint: 'رمز مدينة الانطلاق، مثل DOH للدوحة.',
    country: 'بلد الحساب',
    countryHint: 'رمز ISO المكوّن من حرفين لبلد الحساب.',
    updateCredentials:
      'تحديث كلمة المرور والرقم السري للحساب (اتركه غير محدد للاحتفاظ بالبيانات المحفوظة)',
    credentialsRequired: 'كلمة المرور والرقم السري مطلوبان لإكمال الربط الأول',
    password: 'كلمة المرور',
    accountPin: 'الرقم السري للحساب (PIN)',
    service: 'الخدمة',
    serviceDescription:
      'تستخدم سوقنا الخدمة المحلية عندما يطابق بلد الوجهة بلد الحساب، وتستخدم الخدمة الدولية لبقية الوجهات.',
    domesticService: 'خدمة الطرود المحلية',
    domesticHint: 'عادةً OND؛ تأكد من الرمز المفعّل في حسابك.',
    internationalService: 'خدمة الطرود الدولية',
    internationalHint: 'PPX هي خدمة الطرود السريعة ذات الأولوية للشحن عبر الحدود.',
    pickupAddress: 'عنوان الاستلام',
    addressLine1: 'العنوان — السطر الأول',
    addressLine2: 'العنوان — السطر الثاني (اختياري)',
    city: 'المدينة',
    countryCode: 'رمز البلد',
    postalCode: 'الرمز البريدي',
    contactName: 'اسم جهة الاتصال',
    contactPhone: 'هاتف جهة الاتصال',
    contactEmail: 'بريد جهة الاتصال',
    defaultParcel: 'الطرد الافتراضي',
    weight: 'الوزن (كجم)',
    length: 'الطول (سم)',
    width: 'العرض (سم)',
    height: 'الارتفاع (سم)',
  },
} as const;
